App\Entity\Location:
    properties:
        city:
            - NotBlank: { groups: ['create', 'edit'] }
            - Length: { min: 2, max: 255, groups: ['create', 'edit'] }

        country:
            - NotBlank: { groups: ['create', 'edit'] }
            - Length: { min: 2, max: 100, groups: ['create', 'edit'] }

        latitude:
            - NotBlank: { groups: ['create'] }
            - Range: { min: -90, max: 90, groups: ['create', 'edit'] }

        longitude:
            - NotBlank: { groups: ['create'] }
            - Range: { min: -180, max: 180, groups: ['create', 'edit'] }

App\Entity\Measurement:
    properties:
        celsius:
            - NotBlank: { groups: ['create', 'edit'] }
            - Range: { min: -50, max: 60, groups: ['create', 'edit'] }

        date:
            - NotBlank: { groups: ['create', 'edit'] }

        location:
            - NotNull: { groups: ['create', 'edit'] }
